print("Please enter the following information:")
print(" ")
first = input("First name: ")
last = input("Last name: ")
email = input("Email address: ")
number = input("Phone number: ")
job = input("Job title: ")
ID = input("ID Number: ")
hair = input('Hair color: ')
eyes = input('Eye color: ')
training = input('Have you completed advanced training? Y/N: ')
month = input('What month did you start working here: ')
if training == 'y' or 'Y':
    print(" ")
    print("The ID Card is:")
    print("----------------------------------")
    print(last.upper()+",",first)
    print(job.title())
    print("ID:",ID)
    print(" ")
    print(email.lower())
    print(number)
    print (f'Hair: {hair.capitalize():10} Eyes: {eyes.capitalize()}')
    print(f'Month: {month.capitalize():10} Training: Yes')   
    print("----------------------------------")
else:
    print(" ")
    print("The ID Card is:")
    print("----------------------------------")
    print(last.upper()+",",first)
    print(job.title())
    print("ID:",ID)
    print(" ")
    print(email.lower())
    print(number)
    print (f'Hair: {hair.capitalize():10} Eyes: {eyes.capitalize()}')
    print(f'Month: {month.capitalize():10} Training: No')
    print("----------------------------------")